///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NewDM2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Add_server recording.
    /// </summary>
    [TestModule("1e321baf-070f-4da2-be95-aab433209b51", ModuleType.Recording, 1)]
    public partial class Add_server : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NewDM2Repository repository.
        /// </summary>
        public static NewDM2Repository repo = NewDM2Repository.Instance;

        static Add_server instance = new Add_server();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Add_server()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Add_server Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IDERASQLDiagnosticManagerSQLdmRepos.FilesMenu' at 11;14.", repo.IDERASQLDiagnosticManagerSQLdmRepos.FilesMenuInfo, new RecordItemIndex(0));
            repo.IDERASQLDiagnosticManagerSQLdmRepos.FilesMenu.Click("11;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLdmDesktopClient.ManageServers' at 36;6.", repo.SQLdmDesktopClient.ManageServersInfo, new RecordItemIndex(1));
            repo.SQLdmDesktopClient.ManageServers.Click("36;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ManageServersDialog.AddButton' at 35;10.", repo.ManageServersDialog.AddButtonInfo, new RecordItemIndex(2));
            repo.ManageServersDialog.AddButton.Click("35;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddServersWizard.NextButton' at 40;10.", repo.AddServersWizard.NextButtonInfo, new RecordItemIndex(3));
            repo.AddServersWizard.NextButton.Click("40;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddServersWizard.NextButton' at 40;10.", repo.AddServersWizard.NextButtonInfo, new RecordItemIndex(4));
            repo.AddServersWizard.NextButton.Click("40;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddServersWizard.Password' at 89;4.", repo.AddServersWizard.PasswordInfo, new RecordItemIndex(5));
            repo.AddServersWizard.Password.Click("89;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test1' with focus on 'AddServersWizard.Password'.", repo.AddServersWizard.PasswordInfo, new RecordItemIndex(6));
            repo.AddServersWizard.Password.PressKeys("test1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddServersWizard.AddInstancesButton' at 41;12.", repo.AddServersWizard.AddInstancesButtonInfo, new RecordItemIndex(7));
            repo.AddServersWizard.AddInstancesButton.Click("41;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddServersWizard.NextButton' at 30;10.", repo.AddServersWizard.NextButtonInfo, new RecordItemIndex(8));
            repo.AddServersWizard.NextButton.Click("30;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddServersWizard.NextButton' at 30;10.", repo.AddServersWizard.NextButtonInfo, new RecordItemIndex(9));
            repo.AddServersWizard.NextButton.Click("30;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddServersWizard.EnableQueryMonitorTraceCheckBox' at 8;6.", repo.AddServersWizard.EnableQueryMonitorTraceCheckBoxInfo, new RecordItemIndex(10));
            repo.AddServersWizard.EnableQueryMonitorTraceCheckBox.Click("8;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddServersWizard.NextButton' at 26;9.", repo.AddServersWizard.NextButtonInfo, new RecordItemIndex(11));
            repo.AddServersWizard.NextButton.Click("26;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddServersWizard.NextButton' at 26;9.", repo.AddServersWizard.NextButtonInfo, new RecordItemIndex(12));
            repo.AddServersWizard.NextButton.Click("26;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddServersWizard.NextButton1' at 26;9.", repo.AddServersWizard.NextButton1Info, new RecordItemIndex(13));
            repo.AddServersWizard.NextButton1.Click("26;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ManageServersDialog.Button1' at 42;6.", repo.ManageServersDialog.Button1Info, new RecordItemIndex(14));
            repo.ManageServersDialog.Button1.Click("42;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ManageServersDialog.OkButton' at 37;9.", repo.ManageServersDialog.OkButtonInfo, new RecordItemIndex(15));
            repo.ManageServersDialog.OkButton.Click("37;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IDERASQLDiagnosticManagerSQLdmRepos.UserViewTreeView' at 98;110.", repo.IDERASQLDiagnosticManagerSQLdmRepos.UserViewTreeViewInfo, new RecordItemIndex(16));
            repo.IDERASQLDiagnosticManagerSQLdmRepos.UserViewTreeView.Click("98;110");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'IDERASQLDiagnosticManagerSQLdmRepos.UserViewTreeView'.", repo.IDERASQLDiagnosticManagerSQLdmRepos.UserViewTreeViewInfo, new RecordItemIndex(17));
            Validate.Exists(repo.IDERASQLDiagnosticManagerSQLdmRepos.UserViewTreeViewInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
