///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NewDM2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Create_view recording.
    /// </summary>
    [TestModule("b95d6861-c0d8-455d-aa0c-773539e74436", ModuleType.Recording, 1)]
    public partial class Create_view : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NewDM2Repository repository.
        /// </summary>
        public static NewDM2Repository repo = NewDM2Repository.Instance;

        static Create_view instance = new Create_view();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Create_view()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Create_view Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IDERASQLDiagnosticManagerSQLdmRepos.FilesMenu' at 12;17.", repo.IDERASQLDiagnosticManagerSQLdmRepos.FilesMenuInfo, new RecordItemIndex(0));
            repo.IDERASQLDiagnosticManagerSQLdmRepos.FilesMenu.Click("12;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLdmDesktopClient.CreateView' at 18;3.", repo.SQLdmDesktopClient.CreateViewInfo, new RecordItemIndex(1));
            repo.SQLdmDesktopClient.CreateView.Click("18;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'StaticViewPropertiesDialog.Text' at 135;7.", repo.StaticViewPropertiesDialog.TextInfo, new RecordItemIndex(2));
            repo.StaticViewPropertiesDialog.Text.Click("135;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test13' with focus on 'StaticViewPropertiesDialog.Text'.", repo.StaticViewPropertiesDialog.TextInfo, new RecordItemIndex(3));
            repo.StaticViewPropertiesDialog.Text.PressKeys("test13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'StaticViewPropertiesDialog.Text1' at 101;5.", repo.StaticViewPropertiesDialog.Text1Info, new RecordItemIndex(4));
            repo.StaticViewPropertiesDialog.Text1.Click("101;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '16' with focus on 'StaticViewPropertiesDialog.Text1'.", repo.StaticViewPropertiesDialog.Text1Info, new RecordItemIndex(5));
            repo.StaticViewPropertiesDialog.Text1.PressKeys("16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'StaticViewPropertiesDialog.CELSYSBLR000241MSSQLSERVER16' at 8;5.", repo.StaticViewPropertiesDialog.CELSYSBLR000241MSSQLSERVER16Info, new RecordItemIndex(6));
            repo.StaticViewPropertiesDialog.CELSYSBLR000241MSSQLSERVER16.Click("8;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'StaticViewPropertiesDialog.AddButton' at 53;12.", repo.StaticViewPropertiesDialog.AddButtonInfo, new RecordItemIndex(7));
            repo.StaticViewPropertiesDialog.AddButton.Click("53;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'StaticViewPropertiesDialog.OkButton' at 34;16.", repo.StaticViewPropertiesDialog.OkButtonInfo, new RecordItemIndex(8));
            repo.StaticViewPropertiesDialog.OkButton.Click("34;16");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
