///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NewDM2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The graph_page recording.
    /// </summary>
    [TestModule("55cda16b-0810-42ea-acec-b717f5317a8e", ModuleType.Recording, 1)]
    public partial class graph_page : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NewDM2Repository repository.
        /// </summary>
        public static NewDM2Repository repo = NewDM2Repository.Instance;

        static graph_page instance = new graph_page();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public graph_page()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static graph_page Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IDERASQLDiagnosticManagerSQLdmRepos.FilesMenu' at 11;12.", repo.IDERASQLDiagnosticManagerSQLdmRepos.FilesMenuInfo, new RecordItemIndex(0));
            repo.IDERASQLDiagnosticManagerSQLdmRepos.FilesMenu.Click("11;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLdmDesktopClient.CreateView' at 27;4.", repo.SQLdmDesktopClient.CreateViewInfo, new RecordItemIndex(1));
            repo.SQLdmDesktopClient.CreateView.Click("27;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'check' with focus on 'IDERASQLDiagnosticManagerSQLdmRepos.FilesMenu'.", repo.IDERASQLDiagnosticManagerSQLdmRepos.FilesMenuInfo, new RecordItemIndex(2));
            repo.IDERASQLDiagnosticManagerSQLdmRepos.FilesMenu.PressKeys("check");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'StaticViewPropertiesDialog.ChkAll' at 11;13.", repo.StaticViewPropertiesDialog.ChkAllInfo, new RecordItemIndex(3));
            repo.StaticViewPropertiesDialog.ChkAll.Click("11;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'StaticViewPropertiesDialog.AddButton' at 42;8.", repo.StaticViewPropertiesDialog.AddButtonInfo, new RecordItemIndex(4));
            repo.StaticViewPropertiesDialog.AddButton.Click("42;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'StaticViewPropertiesDialog.OkButton' at 27;12.", repo.StaticViewPropertiesDialog.OkButtonInfo, new RecordItemIndex(5));
            repo.StaticViewPropertiesDialog.OkButton.Click("27;12");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
