///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace NewDM2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the NewDM2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("a7e4b245-c6e1-4077-8b08-fc349955bf82")]
    public partial class NewDM2Repository : RepoGenBaseFolder
    {
        static NewDM2Repository instance = new NewDM2Repository();
        NewDM2RepositoryFolders.IDERASQLDiagnosticManagerSQLdmReposAppFolder _iderasqldiagnosticmanagersqldmrepos;
        NewDM2RepositoryFolders.SQLdmDesktopClientAppFolder _sqldmdesktopclient;
        NewDM2RepositoryFolders.StaticViewPropertiesDialogAppFolder _staticviewpropertiesdialog;
        NewDM2RepositoryFolders.ExceptionMessageBoxFormAppFolder _exceptionmessageboxform;
        NewDM2RepositoryFolders.CustomCounterWizardAppFolder _customcounterwizard;
        NewDM2RepositoryFolders.CustomSearchDialogBoxAppFolder _customsearchdialogbox;
        NewDM2RepositoryFolders.NotificationRulesDialogAppFolder _notificationrulesdialog;
        NewDM2RepositoryFolders.NotificationRuleDialogAppFolder _notificationruledialog;
        NewDM2RepositoryFolders.BlankAppFolder _blank;
        NewDM2RepositoryFolders.ServerSelectionDialogAppFolder _serverselectiondialog;
        NewDM2RepositoryFolders.ManageServersDialogAppFolder _manageserversdialog;
        NewDM2RepositoryFolders.AddServersWizardAppFolder _addserverswizard;

        /// <summary>
        /// Gets the singleton class instance representing the NewDM2Repository element repository.
        /// </summary>
        [RepositoryFolder("a7e4b245-c6e1-4077-8b08-fc349955bf82")]
        public static NewDM2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public NewDM2Repository() 
            : base("NewDM2Repository", "/", null, 0, false, "a7e4b245-c6e1-4077-8b08-fc349955bf82", ".\\RepositoryImages\\NewDM2Repositorya7e4b245.rximgres")
        {
            _iderasqldiagnosticmanagersqldmrepos = new NewDM2RepositoryFolders.IDERASQLDiagnosticManagerSQLdmReposAppFolder(this);
            _sqldmdesktopclient = new NewDM2RepositoryFolders.SQLdmDesktopClientAppFolder(this);
            _staticviewpropertiesdialog = new NewDM2RepositoryFolders.StaticViewPropertiesDialogAppFolder(this);
            _exceptionmessageboxform = new NewDM2RepositoryFolders.ExceptionMessageBoxFormAppFolder(this);
            _customcounterwizard = new NewDM2RepositoryFolders.CustomCounterWizardAppFolder(this);
            _customsearchdialogbox = new NewDM2RepositoryFolders.CustomSearchDialogBoxAppFolder(this);
            _notificationrulesdialog = new NewDM2RepositoryFolders.NotificationRulesDialogAppFolder(this);
            _notificationruledialog = new NewDM2RepositoryFolders.NotificationRuleDialogAppFolder(this);
            _blank = new NewDM2RepositoryFolders.BlankAppFolder(this);
            _serverselectiondialog = new NewDM2RepositoryFolders.ServerSelectionDialogAppFolder(this);
            _manageserversdialog = new NewDM2RepositoryFolders.ManageServersDialogAppFolder(this);
            _addserverswizard = new NewDM2RepositoryFolders.AddServersWizardAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a7e4b245-c6e1-4077-8b08-fc349955bf82")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The IDERASQLDiagnosticManagerSQLdmRepos folder.
        /// </summary>
        [RepositoryFolder("9597f5b2-0fb6-4d03-8e5d-25ad71afc93f")]
        public virtual NewDM2RepositoryFolders.IDERASQLDiagnosticManagerSQLdmReposAppFolder IDERASQLDiagnosticManagerSQLdmRepos
        {
            get { return _iderasqldiagnosticmanagersqldmrepos; }
        }

        /// <summary>
        /// The SQLdmDesktopClient folder.
        /// </summary>
        [RepositoryFolder("be38e4a4-f095-4956-a200-ff54b41fa34f")]
        public virtual NewDM2RepositoryFolders.SQLdmDesktopClientAppFolder SQLdmDesktopClient
        {
            get { return _sqldmdesktopclient; }
        }

        /// <summary>
        /// The StaticViewPropertiesDialog folder.
        /// </summary>
        [RepositoryFolder("8cd63395-5095-424f-8971-7cf06e83e7b6")]
        public virtual NewDM2RepositoryFolders.StaticViewPropertiesDialogAppFolder StaticViewPropertiesDialog
        {
            get { return _staticviewpropertiesdialog; }
        }

        /// <summary>
        /// The ExceptionMessageBoxForm folder.
        /// </summary>
        [RepositoryFolder("97dd9c44-890e-474c-93c4-d35b071a7641")]
        public virtual NewDM2RepositoryFolders.ExceptionMessageBoxFormAppFolder ExceptionMessageBoxForm
        {
            get { return _exceptionmessageboxform; }
        }

        /// <summary>
        /// The CustomCounterWizard folder.
        /// </summary>
        [RepositoryFolder("b65f8005-185a-4a02-a296-714bbd7ae545")]
        public virtual NewDM2RepositoryFolders.CustomCounterWizardAppFolder CustomCounterWizard
        {
            get { return _customcounterwizard; }
        }

        /// <summary>
        /// The CustomSearchDialogBox folder.
        /// </summary>
        [RepositoryFolder("6ca25238-9f37-4ef1-b521-72443422b0b7")]
        public virtual NewDM2RepositoryFolders.CustomSearchDialogBoxAppFolder CustomSearchDialogBox
        {
            get { return _customsearchdialogbox; }
        }

        /// <summary>
        /// The NotificationRulesDialog folder.
        /// </summary>
        [RepositoryFolder("f5961d7b-39ac-4604-98c6-3cca4d9cd709")]
        public virtual NewDM2RepositoryFolders.NotificationRulesDialogAppFolder NotificationRulesDialog
        {
            get { return _notificationrulesdialog; }
        }

        /// <summary>
        /// The NotificationRuleDialog folder.
        /// </summary>
        [RepositoryFolder("80dcb981-60f4-44ba-8190-b44d21632948")]
        public virtual NewDM2RepositoryFolders.NotificationRuleDialogAppFolder NotificationRuleDialog
        {
            get { return _notificationruledialog; }
        }

        /// <summary>
        /// The Blank folder.
        /// </summary>
        [RepositoryFolder("3e2b5a9d-fd35-45c9-8271-5ee27b7e06e5")]
        public virtual NewDM2RepositoryFolders.BlankAppFolder Blank
        {
            get { return _blank; }
        }

        /// <summary>
        /// The ServerSelectionDialog folder.
        /// </summary>
        [RepositoryFolder("6a82086e-527e-4100-a04d-5e360e1a4b40")]
        public virtual NewDM2RepositoryFolders.ServerSelectionDialogAppFolder ServerSelectionDialog
        {
            get { return _serverselectiondialog; }
        }

        /// <summary>
        /// The ManageServersDialog folder.
        /// </summary>
        [RepositoryFolder("0008cd3a-b890-40cb-a740-ddee9bba6974")]
        public virtual NewDM2RepositoryFolders.ManageServersDialogAppFolder ManageServersDialog
        {
            get { return _manageserversdialog; }
        }

        /// <summary>
        /// The AddServersWizard folder.
        /// </summary>
        [RepositoryFolder("b9cd2e58-9bc3-4017-a59a-b2852fe08462")]
        public virtual NewDM2RepositoryFolders.AddServersWizardAppFolder AddServersWizard
        {
            get { return _addserverswizard; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class NewDM2RepositoryFolders
    {
        /// <summary>
        /// The IDERASQLDiagnosticManagerSQLdmReposAppFolder folder.
        /// </summary>
        [RepositoryFolder("9597f5b2-0fb6-4d03-8e5d-25ad71afc93f")]
        public partial class IDERASQLDiagnosticManagerSQLdmReposAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _filesmenuInfo;
            RepoItemInfo _userviewstreeviewInfo;
            RepoItemInfo _demo3Info;
            RepoItemInfo _administrationInfo;
            RepoItemInfo _featureheaderlabelInfo;
            RepoItemInfo _buttongroupcustomcounterstoolstooInfo;
            RepoItemInfo _alertsInfo;
            RepoItemInfo _alertactionsandresponsesInfo;
            RepoItemInfo _userviewtreeviewInfo;

            /// <summary>
            /// Creates a new IDERASQLDiagnosticManagerSQLdmRepos  folder.
            /// </summary>
            public IDERASQLDiagnosticManagerSQLdmReposAppFolder(RepoGenBaseFolder parentFolder) :
                    base("IDERASQLDiagnosticManagerSQLdmRepos", "/form[@title>'IDERA SQL Diagnostic Manager']", parentFolder, 30000, null, true, "9597f5b2-0fb6-4d03-8e5d-25ad71afc93f", "")
            {
                _filesmenuInfo = new RepoItemInfo(this, "FilesMenu", "container/container[1]/menubar[3]/menuitem[@automationid='filesMenu']", ".//menuitem[@automationid='filesMenu']", 30000, null, "6bc8bf83-5dbf-4cb3-9946-b03bd94555da");
                _userviewstreeviewInfo = new RepoItemInfo(this, "UserViewsTreeView", "statusbar[@automationid='statusBar']/?/?/container[@automationid='LeftNavPane']/container[@automationid='navigationPaneHost']//tree[@controlname='userViewsTreeView']", ".//tree[@controlname='userViewsTreeView']", 30000, null, "c05f06de-5059-43f7-94d0-b3584ced417e");
                _demo3Info = new RepoItemInfo(this, "Demo3", "statusbar[@automationid='statusBar']/?/?/container[@automationid='LeftNavPane']/container[@automationid='navigationPaneHost']//tree[@controlname='userViewsTreeView']/treeitem[@accessiblename='demo (3)']", ".//treeitem[@accessiblename='demo (3)']", 30000, null, "2c18890f-4132-4ca6-870d-43b867a82420");
                _administrationInfo = new RepoItemInfo(this, "Administration", ".//tabpagelist[@automationid='topMenu']/tabpage[@automationid='administrationMenu']/text[@caption='Administration']", ".//text[@caption='Administration']", 30000, null, "ba495f1e-e5ec-4337-b63f-14d19c1d5876");
                _featureheaderlabelInfo = new RepoItemInfo(this, "FeatureHeaderLabel", "statusbar[@automationid='statusBar']/?/?/container[@automationid='viewContainer']/container[@automationid='windowsFormsHostControl']/?/?/container[@controlname='_child']//container[@controlname='featureButtonCustomCounter']/?/?/text[@caption='Custom Counters']", ".//text[@caption='Custom Counters' and @controlname='featureHeaderLabel']", 30000, null, "1ef7ec15-8499-4fa2-939f-57b3c8d59daa");
                _buttongroupcustomcounterstoolstooInfo = new RepoItemInfo(this, "ButtonGroupCustomCountersToolsToo", "statusbar[@automationid='statusBar']/?/?/container[@automationid='viewContainer']/container[@automationid='windowsFormsHostControl']//container[@automationid='Ribbon']/container[@automationid='Lower Ribbon']/container[@automationid='Group : CustomCounters']/button[@automationid='[Group : CustomCounters Tools] Tool : createCounterButton - Index : 0 ']", ".//button[@automationid='[Group : CustomCounters Tools] Tool : createCounterButton - Index : 0 ']", 30000, null, "d7ef46e1-d8dd-4aea-b419-17b3044a7cbb");
                _alertsInfo = new RepoItemInfo(this, "Alerts", ".//tabpagelist[@automationid='topMenu']/tabpage[@automationid='alertsMenu']/text[@caption='Alerts']", ".//text[@caption='Alerts']", 30000, null, "b8b3d0c9-660d-43b2-b69a-3251d7dfa41c");
                _alertactionsandresponsesInfo = new RepoItemInfo(this, "AlertActionsAndResponses", "statusbar[@automationid='statusBar']/?/?/container[@automationid='LeftNavPane']/container[@automationid='navigationPaneHost']//link[@url>'Alert Actions and Respons']/?/?/link[@accessiblename>'Alert Actions and Respons']", ".//link[@accessiblename>'Alert Actions and Respons']", 30000, null, "9a2da591-a2f9-4a53-b47c-4405d372821f");
                _userviewtreeviewInfo = new RepoItemInfo(this, "UserViewTreeView", "statusbar[@automationid='statusBar']/?/?/container[@automationid='LeftNavPane']/container[@automationid='navigationPaneHost']//tree[@controlname='userViewTreeView']", ".//tree[@controlname='userViewTreeView']", 30000, null, "acb4f389-b28a-4aa7-b8a9-245e90872afc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9597f5b2-0fb6-4d03-8e5d-25ad71afc93f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9597f5b2-0fb6-4d03-8e5d-25ad71afc93f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FilesMenu item.
            /// </summary>
            [RepositoryItem("6bc8bf83-5dbf-4cb3-9946-b03bd94555da")]
            public virtual Ranorex.MenuItem FilesMenu
            {
                get
                {
                    return _filesmenuInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The FilesMenu item info.
            /// </summary>
            [RepositoryItemInfo("6bc8bf83-5dbf-4cb3-9946-b03bd94555da")]
            public virtual RepoItemInfo FilesMenuInfo
            {
                get
                {
                    return _filesmenuInfo;
                }
            }

            /// <summary>
            /// The UserViewsTreeView item.
            /// </summary>
            [RepositoryItem("c05f06de-5059-43f7-94d0-b3584ced417e")]
            public virtual Ranorex.Tree UserViewsTreeView
            {
                get
                {
                    return _userviewstreeviewInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The UserViewsTreeView item info.
            /// </summary>
            [RepositoryItemInfo("c05f06de-5059-43f7-94d0-b3584ced417e")]
            public virtual RepoItemInfo UserViewsTreeViewInfo
            {
                get
                {
                    return _userviewstreeviewInfo;
                }
            }

            /// <summary>
            /// The Demo3 item.
            /// </summary>
            [RepositoryItem("2c18890f-4132-4ca6-870d-43b867a82420")]
            public virtual Ranorex.TreeItem Demo3
            {
                get
                {
                    return _demo3Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Demo3 item info.
            /// </summary>
            [RepositoryItemInfo("2c18890f-4132-4ca6-870d-43b867a82420")]
            public virtual RepoItemInfo Demo3Info
            {
                get
                {
                    return _demo3Info;
                }
            }

            /// <summary>
            /// The Administration item.
            /// </summary>
            [RepositoryItem("ba495f1e-e5ec-4337-b63f-14d19c1d5876")]
            public virtual Ranorex.Text Administration
            {
                get
                {
                    return _administrationInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Administration item info.
            /// </summary>
            [RepositoryItemInfo("ba495f1e-e5ec-4337-b63f-14d19c1d5876")]
            public virtual RepoItemInfo AdministrationInfo
            {
                get
                {
                    return _administrationInfo;
                }
            }

            /// <summary>
            /// The FeatureHeaderLabel item.
            /// </summary>
            [RepositoryItem("1ef7ec15-8499-4fa2-939f-57b3c8d59daa")]
            public virtual Ranorex.Text FeatureHeaderLabel
            {
                get
                {
                    return _featureheaderlabelInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FeatureHeaderLabel item info.
            /// </summary>
            [RepositoryItemInfo("1ef7ec15-8499-4fa2-939f-57b3c8d59daa")]
            public virtual RepoItemInfo FeatureHeaderLabelInfo
            {
                get
                {
                    return _featureheaderlabelInfo;
                }
            }

            /// <summary>
            /// The ButtonGroupCustomCountersToolsToo item.
            /// </summary>
            [RepositoryItem("d7ef46e1-d8dd-4aea-b419-17b3044a7cbb")]
            public virtual Ranorex.Button ButtonGroupCustomCountersToolsToo
            {
                get
                {
                    return _buttongroupcustomcounterstoolstooInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonGroupCustomCountersToolsToo item info.
            /// </summary>
            [RepositoryItemInfo("d7ef46e1-d8dd-4aea-b419-17b3044a7cbb")]
            public virtual RepoItemInfo ButtonGroupCustomCountersToolsTooInfo
            {
                get
                {
                    return _buttongroupcustomcounterstoolstooInfo;
                }
            }

            /// <summary>
            /// The Alerts item.
            /// </summary>
            [RepositoryItem("b8b3d0c9-660d-43b2-b69a-3251d7dfa41c")]
            public virtual Ranorex.Text Alerts
            {
                get
                {
                    return _alertsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Alerts item info.
            /// </summary>
            [RepositoryItemInfo("b8b3d0c9-660d-43b2-b69a-3251d7dfa41c")]
            public virtual RepoItemInfo AlertsInfo
            {
                get
                {
                    return _alertsInfo;
                }
            }

            /// <summary>
            /// The AlertActionsAndResponses item.
            /// </summary>
            [RepositoryItem("9a2da591-a2f9-4a53-b47c-4405d372821f")]
            public virtual Ranorex.Link AlertActionsAndResponses
            {
                get
                {
                    return _alertactionsandresponsesInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The AlertActionsAndResponses item info.
            /// </summary>
            [RepositoryItemInfo("9a2da591-a2f9-4a53-b47c-4405d372821f")]
            public virtual RepoItemInfo AlertActionsAndResponsesInfo
            {
                get
                {
                    return _alertactionsandresponsesInfo;
                }
            }

            /// <summary>
            /// The UserViewTreeView item.
            /// </summary>
            [RepositoryItem("acb4f389-b28a-4aa7-b8a9-245e90872afc")]
            public virtual Ranorex.Tree UserViewTreeView
            {
                get
                {
                    return _userviewtreeviewInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The UserViewTreeView item info.
            /// </summary>
            [RepositoryItemInfo("acb4f389-b28a-4aa7-b8a9-245e90872afc")]
            public virtual RepoItemInfo UserViewTreeViewInfo
            {
                get
                {
                    return _userviewtreeviewInfo;
                }
            }
        }

        /// <summary>
        /// The SQLdmDesktopClientAppFolder folder.
        /// </summary>
        [RepositoryFolder("be38e4a4-f095-4956-a200-ff54b41fa34f")]
        public partial class SQLdmDesktopClientAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _createviewInfo;
            RepoItemInfo _deletedemoInfo;
            RepoItemInfo _manageserversInfo;

            /// <summary>
            /// Creates a new SQLdmDesktopClient  folder.
            /// </summary>
            public SQLdmDesktopClientAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SQLdmDesktopClient", "/contextmenu[@processname='SQLdmDesktopClient']", parentFolder, 30000, null, false, "be38e4a4-f095-4956-a200-ff54b41fa34f", "")
            {
                _createviewInfo = new RepoItemInfo(this, "CreateView", "?/?/text[@caption='Create View']", "?/?/text[@caption='Create View']", 30000, null, "c991b869-0936-4b83-b0b9-601864951790");
                _deletedemoInfo = new RepoItemInfo(this, "DeleteDemo", "menuitem[@name='Delete \"demo\"']", "menuitem[@name='Delete \"demo\"']", 30000, null, "7058c079-37b9-463f-a120-e78fddb09e7f");
                _manageserversInfo = new RepoItemInfo(this, "ManageServers", "?/?/text[@caption='Manage Servers']", "?/?/text[@caption='Manage Servers']", 30000, null, "cde85998-da8c-4e8d-b8b9-f04c0e6ebb53");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("be38e4a4-f095-4956-a200-ff54b41fa34f")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("be38e4a4-f095-4956-a200-ff54b41fa34f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CreateView item.
            /// </summary>
            [RepositoryItem("c991b869-0936-4b83-b0b9-601864951790")]
            public virtual Ranorex.Text CreateView
            {
                get
                {
                    return _createviewInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CreateView item info.
            /// </summary>
            [RepositoryItemInfo("c991b869-0936-4b83-b0b9-601864951790")]
            public virtual RepoItemInfo CreateViewInfo
            {
                get
                {
                    return _createviewInfo;
                }
            }

            /// <summary>
            /// The DeleteDemo item.
            /// </summary>
            [RepositoryItem("7058c079-37b9-463f-a120-e78fddb09e7f")]
            public virtual Ranorex.MenuItem DeleteDemo
            {
                get
                {
                    return _deletedemoInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The DeleteDemo item info.
            /// </summary>
            [RepositoryItemInfo("7058c079-37b9-463f-a120-e78fddb09e7f")]
            public virtual RepoItemInfo DeleteDemoInfo
            {
                get
                {
                    return _deletedemoInfo;
                }
            }

            /// <summary>
            /// The ManageServers item.
            /// </summary>
            [RepositoryItem("cde85998-da8c-4e8d-b8b9-f04c0e6ebb53")]
            public virtual Ranorex.Text ManageServers
            {
                get
                {
                    return _manageserversInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ManageServers item info.
            /// </summary>
            [RepositoryItemInfo("cde85998-da8c-4e8d-b8b9-f04c0e6ebb53")]
            public virtual RepoItemInfo ManageServersInfo
            {
                get
                {
                    return _manageserversInfo;
                }
            }
        }

        /// <summary>
        /// The StaticViewPropertiesDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("8cd63395-5095-424f-8971-7cf06e83e7b6")]
        public partial class StaticViewPropertiesDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textInfo;
            RepoItemInfo _chkallInfo;
            RepoItemInfo _addbuttonInfo;
            RepoItemInfo _okbuttonInfo;
            RepoItemInfo _pnlformInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _text1Info;
            RepoItemInfo _celsysblr000241mssqlserver16Info;

            /// <summary>
            /// Creates a new StaticViewPropertiesDialog  folder.
            /// </summary>
            public StaticViewPropertiesDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("StaticViewPropertiesDialog", "/form[@title='Create View']", parentFolder, 30000, null, true, "8cd63395-5095-424f-8971-7cf06e83e7b6", "")
            {
                _textInfo = new RepoItemInfo(this, "Text", "?/?/text[@accessiblerole='Text']", "?/?/text[@accessiblerole='Text']", 30000, null, "90d9e2dc-2c42-4aad-9804-13e2dd7b8667");
                _chkallInfo = new RepoItemInfo(this, "ChkAll", "container[@caption='']/container[@controlname='customCheckedFilterListBox']/container[@caption='']//checkbox[@text='All']", ".//checkbox[@text='All']", 30000, null, "e285125b-9eef-476c-aa1e-83127ac8a238");
                _addbuttonInfo = new RepoItemInfo(this, "AddButton", "container[@caption='']/?/?/button[@text='   Add >    ']", ".//button[@text='   Add >    ']", 30000, null, "666e44a3-5286-43ae-aa5d-d5a3f8b3c8c2");
                _okbuttonInfo = new RepoItemInfo(this, "OkButton", "button[@text='Create']", "button[@text='Create']", 30000, null, "b1cbdebe-e898-47f2-83e7-4d9bc704f420");
                _pnlformInfo = new RepoItemInfo(this, "PnlForm", "container[@caption='']", "container[@caption='']", 30000, null, "6d16258b-548c-4c88-9b1b-2e77d669c93a");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", "?/?/button[@accessiblename='Close']", 30000, null, "f44efe14-2691-4ec8-93ad-cdd12b677039");
                _text1Info = new RepoItemInfo(this, "Text1", "container[@caption='']/container[@controlname='customCheckedFilterListBox']/container[@caption='']/container[@caption='']//text[@accessiblerole='Text']", ".//text[@controlname='txtServerSearchbox']/text[@accessiblerole='Text']", 30000, null, "9f54804a-2353-4874-9d79-8a564097e932");
                _celsysblr000241mssqlserver16Info = new RepoItemInfo(this, "CELSYSBLR000241MSSQLSERVER16", "container[@caption='']/container[@controlname='customCheckedFilterListBox']//list[@controlname='checkedListBox1']/?/?/checkbox[@accessiblename>'CELSYSBLR000241\\MSSQLSERV']", ".//checkbox[@accessiblename>'CELSYSBLR000241\\MSSQLSERV']", 30000, null, "e6367306-d4cc-47de-98e8-4d9b72182cac");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8cd63395-5095-424f-8971-7cf06e83e7b6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8cd63395-5095-424f-8971-7cf06e83e7b6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("90d9e2dc-2c42-4aad-9804-13e2dd7b8667")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("90d9e2dc-2c42-4aad-9804-13e2dd7b8667")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The ChkAll item.
            /// </summary>
            [RepositoryItem("e285125b-9eef-476c-aa1e-83127ac8a238")]
            public virtual Ranorex.CheckBox ChkAll
            {
                get
                {
                    return _chkallInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ChkAll item info.
            /// </summary>
            [RepositoryItemInfo("e285125b-9eef-476c-aa1e-83127ac8a238")]
            public virtual RepoItemInfo ChkAllInfo
            {
                get
                {
                    return _chkallInfo;
                }
            }

            /// <summary>
            /// The AddButton item.
            /// </summary>
            [RepositoryItem("666e44a3-5286-43ae-aa5d-d5a3f8b3c8c2")]
            public virtual Ranorex.Button AddButton
            {
                get
                {
                    return _addbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddButton item info.
            /// </summary>
            [RepositoryItemInfo("666e44a3-5286-43ae-aa5d-d5a3f8b3c8c2")]
            public virtual RepoItemInfo AddButtonInfo
            {
                get
                {
                    return _addbuttonInfo;
                }
            }

            /// <summary>
            /// The OkButton item.
            /// </summary>
            [RepositoryItem("b1cbdebe-e898-47f2-83e7-4d9bc704f420")]
            public virtual Ranorex.Button OkButton
            {
                get
                {
                    return _okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OkButton item info.
            /// </summary>
            [RepositoryItemInfo("b1cbdebe-e898-47f2-83e7-4d9bc704f420")]
            public virtual RepoItemInfo OkButtonInfo
            {
                get
                {
                    return _okbuttonInfo;
                }
            }

            /// <summary>
            /// The PnlForm item.
            /// </summary>
            [RepositoryItem("6d16258b-548c-4c88-9b1b-2e77d669c93a")]
            public virtual Ranorex.Container PnlForm
            {
                get
                {
                    return _pnlformInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The PnlForm item info.
            /// </summary>
            [RepositoryItemInfo("6d16258b-548c-4c88-9b1b-2e77d669c93a")]
            public virtual RepoItemInfo PnlFormInfo
            {
                get
                {
                    return _pnlformInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("f44efe14-2691-4ec8-93ad-cdd12b677039")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("f44efe14-2691-4ec8-93ad-cdd12b677039")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The Text1 item.
            /// </summary>
            [RepositoryItem("9f54804a-2353-4874-9d79-8a564097e932")]
            public virtual Ranorex.Text Text1
            {
                get
                {
                    return _text1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1 item info.
            /// </summary>
            [RepositoryItemInfo("9f54804a-2353-4874-9d79-8a564097e932")]
            public virtual RepoItemInfo Text1Info
            {
                get
                {
                    return _text1Info;
                }
            }

            /// <summary>
            /// The CELSYSBLR000241MSSQLSERVER16 item.
            /// </summary>
            [RepositoryItem("e6367306-d4cc-47de-98e8-4d9b72182cac")]
            public virtual Ranorex.CheckBox CELSYSBLR000241MSSQLSERVER16
            {
                get
                {
                    return _celsysblr000241mssqlserver16Info.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The CELSYSBLR000241MSSQLSERVER16 item info.
            /// </summary>
            [RepositoryItemInfo("e6367306-d4cc-47de-98e8-4d9b72182cac")]
            public virtual RepoItemInfo CELSYSBLR000241MSSQLSERVER16Info
            {
                get
                {
                    return _celsysblr000241mssqlserver16Info;
                }
            }
        }

        /// <summary>
        /// The ExceptionMessageBoxFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("97dd9c44-890e-474c-93c4-d35b071a7641")]
        public partial class ExceptionMessageBoxFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _button1Info;
            RepoItemInfo _showdetailsInfo;
            RepoItemInfo _cellcolumnheadertotalactivealertcounInfo;
            RepoItemInfo _texteditoreditareaInfo;

            /// <summary>
            /// Creates a new ExceptionMessageBoxForm  folder.
            /// </summary>
            public ExceptionMessageBoxFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ExceptionMessageBoxForm", "/form[@title>'IDERA SQL Diagnostic Mana']", parentFolder, 30000, null, true, "97dd9c44-890e-474c-93c4-d35b071a7641", "")
            {
                _button1Info = new RepoItemInfo(this, "Button1", "?/?/container[@controlname='pnlButtons']/button[@text='&Yes']", ".//button[@text='&Yes']", 30000, null, "696e98ee-3bc3-46e6-b6c5-78f40b01796b");
                _showdetailsInfo = new RepoItemInfo(this, "ShowDetails", "element[@automationid='dockMgr']/element[@automationid='SplitPane0']/?/?/element[@automationid='viewContainer']//toolbar[@controlname='headerStrip']/checkbox[@accessiblename='Show Details']", ".//checkbox[@accessiblename='Show Details']", 30000, null, "34ce331a-9eec-431c-8376-fb43e462d2c8");
                _cellcolumnheadertotalactivealertcounInfo = new RepoItemInfo(this, "CellColumnHeaderTotalActiveAlertCoun", "element[@automationid='dockMgr']/element[@automationid='SplitPane0']/element[@automationid='BodyPane']/element[@automationid='viewContainer']/container[@automationid='windowsFormsHostControl']//tree[@automationid='ColScrollRegion: 0, RowScrollRegion: 0']/row[@automationid='Band Headers']/cell[@automationid='[Column Header] TotalActiveAlertCount']", ".//cell[@automationid='[Column Header] TotalActiveAlertCount']", 30000, null, "55e8006f-6c1e-4b5d-ada6-0fa2b54516c8");
                _texteditoreditareaInfo = new RepoItemInfo(this, "TextEditorEditArea", "element[@automationid='dockMgr']/element[@automationid='SplitPane0']/element[@automationid='BodyPane']/element[@automationid='viewContainer']/container[@automationid='windowsFormsHostControl']//tree[@automationid='ColScrollRegion: 0, RowScrollRegion: 0']/treeitem[@automationid='2']/text[@automationid='15']/text[@automationid='[Editor] Edit Area']", ".//text[@name='Instance' and @itemstatus=' !IG_DATA_START!ObjectIdentifier^IG_TOKEN_SEPERATOR^Infragistics.Win.UltraWinGrid.RowColRegionIntersectionUIElement+CellUiaProviderStub^IG_TOKEN_DELIMETER^AssemblyVersion^IG_TOKEN_SEPERATOR^21.2.20212.46^IG_TOKEN_DELIMETER^IsRootStub^IG_TOKEN_SEPERATOR^False^IG_TOKEN_SEPERATOR^4^IG_TOKEN_DELIMETER^DisplayText^IG_TOKEN_SEPERATOR^CELSYSBLR000241\\MSSQLSERVER_16^IG_TOKEN_DELIMETER^!IG_DATA_END!']/text[@automationid='[Editor] Edit Area']", 30000, null, "7a72a39d-f8f5-458a-8f7f-e4ba54a77dff");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("97dd9c44-890e-474c-93c4-d35b071a7641")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("97dd9c44-890e-474c-93c4-d35b071a7641")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("696e98ee-3bc3-46e6-b6c5-78f40b01796b")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("696e98ee-3bc3-46e6-b6c5-78f40b01796b")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }

            /// <summary>
            /// The ShowDetails item.
            /// </summary>
            [RepositoryItem("34ce331a-9eec-431c-8376-fb43e462d2c8")]
            public virtual Ranorex.CheckBox ShowDetails
            {
                get
                {
                    return _showdetailsInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ShowDetails item info.
            /// </summary>
            [RepositoryItemInfo("34ce331a-9eec-431c-8376-fb43e462d2c8")]
            public virtual RepoItemInfo ShowDetailsInfo
            {
                get
                {
                    return _showdetailsInfo;
                }
            }

            /// <summary>
            /// The CellColumnHeaderTotalActiveAlertCoun item.
            /// </summary>
            [RepositoryItem("55e8006f-6c1e-4b5d-ada6-0fa2b54516c8")]
            public virtual Ranorex.Cell CellColumnHeaderTotalActiveAlertCoun
            {
                get
                {
                    return _cellcolumnheadertotalactivealertcounInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellColumnHeaderTotalActiveAlertCoun item info.
            /// </summary>
            [RepositoryItemInfo("55e8006f-6c1e-4b5d-ada6-0fa2b54516c8")]
            public virtual RepoItemInfo CellColumnHeaderTotalActiveAlertCounInfo
            {
                get
                {
                    return _cellcolumnheadertotalactivealertcounInfo;
                }
            }

            /// <summary>
            /// The TextEditorEditArea item.
            /// </summary>
            [RepositoryItem("7a72a39d-f8f5-458a-8f7f-e4ba54a77dff")]
            public virtual Ranorex.Text TextEditorEditArea
            {
                get
                {
                    return _texteditoreditareaInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextEditorEditArea item info.
            /// </summary>
            [RepositoryItemInfo("7a72a39d-f8f5-458a-8f7f-e4ba54a77dff")]
            public virtual RepoItemInfo TextEditorEditAreaInfo
            {
                get
                {
                    return _texteditoreditareaInfo;
                }
            }
        }

        /// <summary>
        /// The CustomCounterWizardAppFolder folder.
        /// </summary>
        [RepositoryFolder("b65f8005-185a-4a02-a296-714bbd7ae545")]
        public partial class CustomCounterWizardAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _nextbuttonInfo;
            RepoItemInfo _instancenameInfo;
            RepoItemInfo _cancelbuttonInfo;

            /// <summary>
            /// Creates a new CustomCounterWizard  folder.
            /// </summary>
            public CustomCounterWizardAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CustomCounterWizard", "/form[@title='Add Custom Counter']", parentFolder, 30000, null, true, "b65f8005-185a-4a02-a296-714bbd7ae545", "")
            {
                _nextbuttonInfo = new RepoItemInfo(this, "NextButton", "?/?/button[@text='&Next >']", "?/?/button[@text='&Next >']", 30000, null, "2251c852-1715-4167-afd3-488aead97a4c");
                _instancenameInfo = new RepoItemInfo(this, "InstanceName", "?/?/container[@controlname='ultraTabWmiCounterPage']/container[@controlname='wmiCounterPage']//combobox[@controlname='wmiServeSearchBox']/text[@name='Instance Name:']", ".//text[@caption='Instance Name:' and @iskeyboardfocusable='True']", 30000, null, "e0d4476c-b7e8-4343-a362-6ae14691dd4a");
                _cancelbuttonInfo = new RepoItemInfo(this, "CancelButton", "?/?/button[@text='Cancel']", "?/?/button[@text='Cancel']", 30000, null, "bc1561ab-4d56-4eba-b180-ad7b5f847162");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b65f8005-185a-4a02-a296-714bbd7ae545")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b65f8005-185a-4a02-a296-714bbd7ae545")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NextButton item.
            /// </summary>
            [RepositoryItem("2251c852-1715-4167-afd3-488aead97a4c")]
            public virtual Ranorex.Button NextButton
            {
                get
                {
                    return _nextbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The NextButton item info.
            /// </summary>
            [RepositoryItemInfo("2251c852-1715-4167-afd3-488aead97a4c")]
            public virtual RepoItemInfo NextButtonInfo
            {
                get
                {
                    return _nextbuttonInfo;
                }
            }

            /// <summary>
            /// The InstanceName item.
            /// </summary>
            [RepositoryItem("e0d4476c-b7e8-4343-a362-6ae14691dd4a")]
            public virtual Ranorex.Text InstanceName
            {
                get
                {
                    return _instancenameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The InstanceName item info.
            /// </summary>
            [RepositoryItemInfo("e0d4476c-b7e8-4343-a362-6ae14691dd4a")]
            public virtual RepoItemInfo InstanceNameInfo
            {
                get
                {
                    return _instancenameInfo;
                }
            }

            /// <summary>
            /// The CancelButton item.
            /// </summary>
            [RepositoryItem("bc1561ab-4d56-4eba-b180-ad7b5f847162")]
            public virtual Ranorex.Button CancelButton
            {
                get
                {
                    return _cancelbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CancelButton item info.
            /// </summary>
            [RepositoryItemInfo("bc1561ab-4d56-4eba-b180-ad7b5f847162")]
            public virtual RepoItemInfo CancelButtonInfo
            {
                get
                {
                    return _cancelbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The CustomSearchDialogBoxAppFolder folder.
        /// </summary>
        [RepositoryFolder("6ca25238-9f37-4ef1-b521-72443422b0b7")]
        public partial class CustomSearchDialogBoxAppFolder : RepoGenBaseFolder
        {
            NewDM2RepositoryFolders.SplitContainer1Folder _splitcontainer1;

            /// <summary>
            /// Creates a new CustomSearchDialogBox  folder.
            /// </summary>
            public CustomSearchDialogBoxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CustomSearchDialogBox", "/form[@title='Instance List']", parentFolder, 30000, null, true, "6ca25238-9f37-4ef1-b521-72443422b0b7", "")
            {
                _splitcontainer1 = new NewDM2RepositoryFolders.SplitContainer1Folder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6ca25238-9f37-4ef1-b521-72443422b0b7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6ca25238-9f37-4ef1-b521-72443422b0b7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SplitContainer1 folder.
            /// </summary>
            [RepositoryFolder("5e21a468-c807-4796-ad89-6bff979e11b7")]
            public virtual NewDM2RepositoryFolders.SplitContainer1Folder SplitContainer1
            {
                get { return _splitcontainer1; }
            }
        }

        /// <summary>
        /// The SplitContainer1Folder folder.
        /// </summary>
        [RepositoryFolder("5e21a468-c807-4796-ad89-6bff979e11b7")]
        public partial class SplitContainer1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _btnokInfo;
            RepoItemInfo _celsysblr000241celsyswtc17Info;
            RepoItemInfo _textInfo;

            /// <summary>
            /// Creates a new SplitContainer1  folder.
            /// </summary>
            public SplitContainer1Folder(RepoGenBaseFolder parentFolder) :
                    base("SplitContainer1", "container[@caption='']/container[@caption='']", parentFolder, 30000, null, false, "5e21a468-c807-4796-ad89-6bff979e11b7", "")
            {
                _btnokInfo = new RepoItemInfo(this, "BtnOk", ".//button[@text='OK']", "", 30000, null, "fe9a3adc-0b97-46cd-bbd3-54785762f0d4");
                _celsysblr000241celsyswtc17Info = new RepoItemInfo(this, "CELSYSBLR000241CELSYSWTC17", ".//list[@controlname='checkedListBoxserver']/?/?/listitem[@accessiblename>'CELSYSBLR000241\\CELSYSWTC']", "", 30000, null, "ac3e5fbc-ad3a-4832-ae66-b24c7262ffe8");
                _textInfo = new RepoItemInfo(this, "Text", ".//text[@accessiblerole='Text']", "", 30000, null, "e578af5d-1556-4515-998b-012d4a45071f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5e21a468-c807-4796-ad89-6bff979e11b7")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5e21a468-c807-4796-ad89-6bff979e11b7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnOk item.
            /// </summary>
            [RepositoryItem("fe9a3adc-0b97-46cd-bbd3-54785762f0d4")]
            public virtual Ranorex.Button BtnOk
            {
                get
                {
                    return _btnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnOk item info.
            /// </summary>
            [RepositoryItemInfo("fe9a3adc-0b97-46cd-bbd3-54785762f0d4")]
            public virtual RepoItemInfo BtnOkInfo
            {
                get
                {
                    return _btnokInfo;
                }
            }

            /// <summary>
            /// The CELSYSBLR000241CELSYSWTC17 item.
            /// </summary>
            [RepositoryItem("ac3e5fbc-ad3a-4832-ae66-b24c7262ffe8")]
            public virtual Ranorex.ListItem CELSYSBLR000241CELSYSWTC17
            {
                get
                {
                    return _celsysblr000241celsyswtc17Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The CELSYSBLR000241CELSYSWTC17 item info.
            /// </summary>
            [RepositoryItemInfo("ac3e5fbc-ad3a-4832-ae66-b24c7262ffe8")]
            public virtual RepoItemInfo CELSYSBLR000241CELSYSWTC17Info
            {
                get
                {
                    return _celsysblr000241celsyswtc17Info;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("e578af5d-1556-4515-998b-012d4a45071f")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("e578af5d-1556-4515-998b-012d4a45071f")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }
        }

        /// <summary>
        /// The NotificationRulesDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("f5961d7b-39ac-4604-98c6-3cca4d9cd709")]
        public partial class NotificationRulesDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addbuttonInfo;
            RepoItemInfo _cancelbuttonInfo;

            /// <summary>
            /// Creates a new NotificationRulesDialog  folder.
            /// </summary>
            public NotificationRulesDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NotificationRulesDialog", "/form[@title>'Alert Actions and Respons']", parentFolder, 30000, null, true, "f5961d7b-39ac-4604-98c6-3cca4d9cd709", "")
            {
                _addbuttonInfo = new RepoItemInfo(this, "AddButton", "?/?/container[@controlname='ultraTabPageControl1']/container[@caption='']//button[@text='Add']", ".//button[@controlname='addButton']", 30000, null, "7922a6b1-c4d0-4ab4-a934-5cae67e6639b");
                _cancelbuttonInfo = new RepoItemInfo(this, "CancelButton", "button[@text='Finish']", "button[@text='Finish']", 30000, null, "0c7885db-808b-42cf-b92c-9ae2baf2de29");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f5961d7b-39ac-4604-98c6-3cca4d9cd709")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f5961d7b-39ac-4604-98c6-3cca4d9cd709")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddButton item.
            /// </summary>
            [RepositoryItem("7922a6b1-c4d0-4ab4-a934-5cae67e6639b")]
            public virtual Ranorex.Button AddButton
            {
                get
                {
                    return _addbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddButton item info.
            /// </summary>
            [RepositoryItemInfo("7922a6b1-c4d0-4ab4-a934-5cae67e6639b")]
            public virtual RepoItemInfo AddButtonInfo
            {
                get
                {
                    return _addbuttonInfo;
                }
            }

            /// <summary>
            /// The CancelButton item.
            /// </summary>
            [RepositoryItem("0c7885db-808b-42cf-b92c-9ae2baf2de29")]
            public virtual Ranorex.Button CancelButton
            {
                get
                {
                    return _cancelbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CancelButton item info.
            /// </summary>
            [RepositoryItemInfo("0c7885db-808b-42cf-b92c-9ae2baf2de29")]
            public virtual RepoItemInfo CancelButtonInfo
            {
                get
                {
                    return _cancelbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The NotificationRuleDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("80dcb981-60f4-44ba-8190-b44d21632948")]
        public partial class NotificationRuleDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textInfo;
            RepoItemInfo _wherethesqlserverinstanceisinahrInfo;
            RepoItemInfo _cancelbuttonInfo;

            /// <summary>
            /// Creates a new NotificationRuleDialog  folder.
            /// </summary>
            public NotificationRuleDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NotificationRuleDialog", "/form[@title='Alert Response']", parentFolder, 30000, null, true, "80dcb981-60f4-44ba-8190-b44d21632948", "")
            {
                _textInfo = new RepoItemInfo(this, "Text", "?/?/text[@accessiblerole='Text']", "?/?/text[@accessiblerole='Text']", 30000, null, "eba5523a-2110-4722-addf-316a152f3670");
                _wherethesqlserverinstanceisinahrInfo = new RepoItemInfo(this, "WhereTheSQLServerInstanceIsInAHr", "?/?/table[@controlname='conditionListBox']/?/?/cell[@text>'Where the SQL Server Instance']", ".//cell[@text>'Where the SQL Server Instance']", 30000, null, "9635269a-a2e3-4b03-818c-f44c052a5cd3");
                _cancelbuttonInfo = new RepoItemInfo(this, "CancelButton", "button[@text='Cancel']", "button[@text='Cancel']", 30000, null, "513c9757-ce97-419f-aefc-8fef237a98f8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("80dcb981-60f4-44ba-8190-b44d21632948")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("80dcb981-60f4-44ba-8190-b44d21632948")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("eba5523a-2110-4722-addf-316a152f3670")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("eba5523a-2110-4722-addf-316a152f3670")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The WhereTheSQLServerInstanceIsInAHr item.
            /// </summary>
            [RepositoryItem("9635269a-a2e3-4b03-818c-f44c052a5cd3")]
            public virtual Ranorex.Cell WhereTheSQLServerInstanceIsInAHr
            {
                get
                {
                    return _wherethesqlserverinstanceisinahrInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The WhereTheSQLServerInstanceIsInAHr item info.
            /// </summary>
            [RepositoryItemInfo("9635269a-a2e3-4b03-818c-f44c052a5cd3")]
            public virtual RepoItemInfo WhereTheSQLServerInstanceIsInAHrInfo
            {
                get
                {
                    return _wherethesqlserverinstanceisinahrInfo;
                }
            }

            /// <summary>
            /// The CancelButton item.
            /// </summary>
            [RepositoryItem("513c9757-ce97-419f-aefc-8fef237a98f8")]
            public virtual Ranorex.Button CancelButton
            {
                get
                {
                    return _cancelbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CancelButton item info.
            /// </summary>
            [RepositoryItemInfo("513c9757-ce97-419f-aefc-8fef237a98f8")]
            public virtual RepoItemInfo CancelButtonInfo
            {
                get
                {
                    return _cancelbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The BlankAppFolder folder.
        /// </summary>
        [RepositoryFolder("3e2b5a9d-fd35-45c9-8271-5ee27b7e06e5")]
        public partial class BlankAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _specifiedlistInfo;

            /// <summary>
            /// Creates a new Blank  folder.
            /// </summary>
            public BlankAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Blank", "/dom[@domain='']", parentFolder, 30000, null, false, "3e2b5a9d-fd35-45c9-8271-5ee27b7e06e5", "")
            {
                _specifiedlistInfo = new RepoItemInfo(this, "SpecifiedList", "?/?/table/tbody/tr[2]/td[@innertext>'and SQL Server Instance is']/?/?/font[@innertext='specified list']", ".//font[@innertext='specified list']", 30000, null, "0ef18c12-45ed-4548-8bb7-2b03a304f0b7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3e2b5a9d-fd35-45c9-8271-5ee27b7e06e5")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3e2b5a9d-fd35-45c9-8271-5ee27b7e06e5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SpecifiedList item.
            /// </summary>
            [RepositoryItem("0ef18c12-45ed-4548-8bb7-2b03a304f0b7")]
            public virtual Ranorex.FontTag SpecifiedList
            {
                get
                {
                    return _specifiedlistInfo.CreateAdapter<Ranorex.FontTag>(true);
                }
            }

            /// <summary>
            /// The SpecifiedList item info.
            /// </summary>
            [RepositoryItemInfo("0ef18c12-45ed-4548-8bb7-2b03a304f0b7")]
            public virtual RepoItemInfo SpecifiedListInfo
            {
                get
                {
                    return _specifiedlistInfo;
                }
            }
        }

        /// <summary>
        /// The ServerSelectionDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("6a82086e-527e-4100-a04d-5e360e1a4b40")]
        public partial class ServerSelectionDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textInfo;
            RepoItemInfo _celsysblr000241celsyswtc17Info;
            RepoItemInfo _btnokInfo;

            /// <summary>
            /// Creates a new ServerSelectionDialog  folder.
            /// </summary>
            public ServerSelectionDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ServerSelectionDialog", "/form[@title='Instances']", parentFolder, 30000, null, true, "6a82086e-527e-4100-a04d-5e360e1a4b40", "")
            {
                _textInfo = new RepoItemInfo(this, "Text", "?/?/text[@accessiblerole='Text']", "?/?/text[@accessiblerole='Text']", 30000, null, "47d340c9-a6d7-4ba0-a708-98ca00c1ac3a");
                _celsysblr000241celsyswtc17Info = new RepoItemInfo(this, "CELSYSBLR000241CELSYSWTC17", "list[@controlname='serverListBox']/?/?/checkbox[@accessiblename>'CELSYSBLR000241\\CELSYSWTC']", ".//checkbox[@accessiblename>'CELSYSBLR000241\\CELSYSWTC']", 30000, null, "336bf41a-a042-44e6-9dac-19217025d617");
                _btnokInfo = new RepoItemInfo(this, "BtnOK", "?/?/button[@text='OK']", "?/?/button[@text='OK']", 30000, null, "f57fb79f-4779-42e6-a45c-70549f9b7329");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6a82086e-527e-4100-a04d-5e360e1a4b40")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6a82086e-527e-4100-a04d-5e360e1a4b40")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("47d340c9-a6d7-4ba0-a708-98ca00c1ac3a")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("47d340c9-a6d7-4ba0-a708-98ca00c1ac3a")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The CELSYSBLR000241CELSYSWTC17 item.
            /// </summary>
            [RepositoryItem("336bf41a-a042-44e6-9dac-19217025d617")]
            public virtual Ranorex.CheckBox CELSYSBLR000241CELSYSWTC17
            {
                get
                {
                    return _celsysblr000241celsyswtc17Info.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The CELSYSBLR000241CELSYSWTC17 item info.
            /// </summary>
            [RepositoryItemInfo("336bf41a-a042-44e6-9dac-19217025d617")]
            public virtual RepoItemInfo CELSYSBLR000241CELSYSWTC17Info
            {
                get
                {
                    return _celsysblr000241celsyswtc17Info;
                }
            }

            /// <summary>
            /// The BtnOK item.
            /// </summary>
            [RepositoryItem("f57fb79f-4779-42e6-a45c-70549f9b7329")]
            public virtual Ranorex.Button BtnOK
            {
                get
                {
                    return _btnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnOK item info.
            /// </summary>
            [RepositoryItemInfo("f57fb79f-4779-42e6-a45c-70549f9b7329")]
            public virtual RepoItemInfo BtnOKInfo
            {
                get
                {
                    return _btnokInfo;
                }
            }
        }

        /// <summary>
        /// The ManageServersDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("0008cd3a-b890-40cb-a740-ddee9bba6974")]
        public partial class ManageServersDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addbuttonInfo;
            RepoItemInfo _button1Info;
            RepoItemInfo _okbuttonInfo;

            /// <summary>
            /// Creates a new ManageServersDialog  folder.
            /// </summary>
            public ManageServersDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ManageServersDialog", "/form[@title='Manage Servers']", parentFolder, 30000, null, true, "0008cd3a-b890-40cb-a740-ddee9bba6974", "")
            {
                _addbuttonInfo = new RepoItemInfo(this, "AddButton", "button[@text='Add']", "button[@text='Add']", 30000, null, "ae7476b7-6a15-4a92-a120-377ac17d6917");
                _button1Info = new RepoItemInfo(this, "Button1", "?/?/container[@controlname='pnlButtons']/button[@text='&Yes']", ".//button[@text='&Yes']", 30000, null, "1ac40c20-5ea9-4edd-803f-a915fbe890bd");
                _okbuttonInfo = new RepoItemInfo(this, "OkButton", "button[@text='OK']", "button[@text='OK']", 30000, null, "9eecefe2-0c59-4967-bc17-9db71a3ce45f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0008cd3a-b890-40cb-a740-ddee9bba6974")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0008cd3a-b890-40cb-a740-ddee9bba6974")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddButton item.
            /// </summary>
            [RepositoryItem("ae7476b7-6a15-4a92-a120-377ac17d6917")]
            public virtual Ranorex.Button AddButton
            {
                get
                {
                    return _addbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddButton item info.
            /// </summary>
            [RepositoryItemInfo("ae7476b7-6a15-4a92-a120-377ac17d6917")]
            public virtual RepoItemInfo AddButtonInfo
            {
                get
                {
                    return _addbuttonInfo;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("1ac40c20-5ea9-4edd-803f-a915fbe890bd")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("1ac40c20-5ea9-4edd-803f-a915fbe890bd")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }

            /// <summary>
            /// The OkButton item.
            /// </summary>
            [RepositoryItem("9eecefe2-0c59-4967-bc17-9db71a3ce45f")]
            public virtual Ranorex.Button OkButton
            {
                get
                {
                    return _okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OkButton item info.
            /// </summary>
            [RepositoryItemInfo("9eecefe2-0c59-4967-bc17-9db71a3ce45f")]
            public virtual RepoItemInfo OkButtonInfo
            {
                get
                {
                    return _okbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The AddServersWizardAppFolder folder.
        /// </summary>
        [RepositoryFolder("b9cd2e58-9bc3-4017-a59a-b2852fe08462")]
        public partial class AddServersWizardAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _nextbuttonInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _addinstancesbuttonInfo;
            RepoItemInfo _enablequerymonitortracecheckboxInfo;
            RepoItemInfo _nextbutton1Info;

            /// <summary>
            /// Creates a new AddServersWizard  folder.
            /// </summary>
            public AddServersWizardAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AddServersWizard", "/form[@title='Add Servers Wizard']", parentFolder, 30000, null, true, "b9cd2e58-9bc3-4017-a59a-b2852fe08462", "")
            {
                _nextbuttonInfo = new RepoItemInfo(this, "NextButton", "?/?/button[@text='&Next >']", "?/?/button[@text='&Next >']", 30000, null, "d69a6292-c9e8-4ff6-9b1c-2ac45f990950");
                _passwordInfo = new RepoItemInfo(this, "Password", "?/?/container[@controlname='ultraTabInstancesPage']/container[@controlname='selectInstancesPage']/?/?/text[@accessiblename='Password:']", ".//text[@accessiblename='Password:']", 30000, null, "b6daf6eb-bf47-482d-92dd-ecc96cb40ef4");
                _addinstancesbuttonInfo = new RepoItemInfo(this, "AddInstancesButton", "?/?/container[@controlname='ultraTabInstancesPage']/?/?/button[@controlname='addInstancesButton']", ".//button[@controlname='addInstancesButton']", 30000, null, "60086ce0-bd6a-4bb1-8224-09972493f218");
                _enablequerymonitortracecheckboxInfo = new RepoItemInfo(this, "EnableQueryMonitorTraceCheckBox", "?/?/container[@controlname='CollectionPage']/container[@controlname='configureCollectionPage']/?/?/checkbox[@controlname='enableQueryMonitorTraceCheckBox']", ".//checkbox[@controlname='enableQueryMonitorTraceCheckBox']", 30000, null, "6c944e51-fc00-4b51-9722-43ceb578131c");
                _nextbutton1Info = new RepoItemInfo(this, "NextButton1", "?/?/button[@text='Finish']", "?/?/button[@text='Finish']", 30000, null, "58fc4a0c-cc2e-4483-8ae8-1af3c947a958");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b9cd2e58-9bc3-4017-a59a-b2852fe08462")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b9cd2e58-9bc3-4017-a59a-b2852fe08462")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NextButton item.
            /// </summary>
            [RepositoryItem("d69a6292-c9e8-4ff6-9b1c-2ac45f990950")]
            public virtual Ranorex.Button NextButton
            {
                get
                {
                    return _nextbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The NextButton item info.
            /// </summary>
            [RepositoryItemInfo("d69a6292-c9e8-4ff6-9b1c-2ac45f990950")]
            public virtual RepoItemInfo NextButtonInfo
            {
                get
                {
                    return _nextbuttonInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("b6daf6eb-bf47-482d-92dd-ecc96cb40ef4")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("b6daf6eb-bf47-482d-92dd-ecc96cb40ef4")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The AddInstancesButton item.
            /// </summary>
            [RepositoryItem("60086ce0-bd6a-4bb1-8224-09972493f218")]
            public virtual Ranorex.Button AddInstancesButton
            {
                get
                {
                    return _addinstancesbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddInstancesButton item info.
            /// </summary>
            [RepositoryItemInfo("60086ce0-bd6a-4bb1-8224-09972493f218")]
            public virtual RepoItemInfo AddInstancesButtonInfo
            {
                get
                {
                    return _addinstancesbuttonInfo;
                }
            }

            /// <summary>
            /// The EnableQueryMonitorTraceCheckBox item.
            /// </summary>
            [RepositoryItem("6c944e51-fc00-4b51-9722-43ceb578131c")]
            public virtual Ranorex.CheckBox EnableQueryMonitorTraceCheckBox
            {
                get
                {
                    return _enablequerymonitortracecheckboxInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The EnableQueryMonitorTraceCheckBox item info.
            /// </summary>
            [RepositoryItemInfo("6c944e51-fc00-4b51-9722-43ceb578131c")]
            public virtual RepoItemInfo EnableQueryMonitorTraceCheckBoxInfo
            {
                get
                {
                    return _enablequerymonitortracecheckboxInfo;
                }
            }

            /// <summary>
            /// The NextButton1 item.
            /// </summary>
            [RepositoryItem("58fc4a0c-cc2e-4483-8ae8-1af3c947a958")]
            public virtual Ranorex.Button NextButton1
            {
                get
                {
                    return _nextbutton1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The NextButton1 item info.
            /// </summary>
            [RepositoryItemInfo("58fc4a0c-cc2e-4483-8ae8-1af3c947a958")]
            public virtual RepoItemInfo NextButton1Info
            {
                get
                {
                    return _nextbutton1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
