///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NewDM2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("c50c2742-2ba8-4ad5-9708-4a6453fa020d", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NewDM2Repository repository.
        /// </summary>
        public static NewDM2Repository repo = NewDM2Repository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IDERASQLDiagnosticManagerSQLdmRepos.FilesMenu' at 12;13.", repo.IDERASQLDiagnosticManagerSQLdmRepos.FilesMenuInfo, new RecordItemIndex(0));
            repo.IDERASQLDiagnosticManagerSQLdmRepos.FilesMenu.Click("12;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SQLdmDesktopClient.CreateView' at 35;6.", repo.SQLdmDesktopClient.CreateViewInfo, new RecordItemIndex(1));
            repo.SQLdmDesktopClient.CreateView.Click("35;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'StaticViewPropertiesDialog.Text' at 190;6.", repo.StaticViewPropertiesDialog.TextInfo, new RecordItemIndex(2));
            repo.StaticViewPropertiesDialog.Text.Click("190;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'demo' with focus on 'StaticViewPropertiesDialog.Text'.", repo.StaticViewPropertiesDialog.TextInfo, new RecordItemIndex(3));
            repo.StaticViewPropertiesDialog.Text.PressKeys("demo");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'StaticViewPropertiesDialog.ChkAll' at 3;19.", repo.StaticViewPropertiesDialog.ChkAllInfo, new RecordItemIndex(4));
            repo.StaticViewPropertiesDialog.ChkAll.Click("3;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'StaticViewPropertiesDialog.AddButton' at 29;10.", repo.StaticViewPropertiesDialog.AddButtonInfo, new RecordItemIndex(5));
            repo.StaticViewPropertiesDialog.AddButton.Click("29;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'StaticViewPropertiesDialog.OkButton' at 26;9.", repo.StaticViewPropertiesDialog.OkButtonInfo, new RecordItemIndex(6));
            repo.StaticViewPropertiesDialog.OkButton.Click("26;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'IDERASQLDiagnosticManagerSQLdmRepos.Demo3' at 35;11.", repo.IDERASQLDiagnosticManagerSQLdmRepos.Demo3Info, new RecordItemIndex(7));
            repo.IDERASQLDiagnosticManagerSQLdmRepos.Demo3.Click(System.Windows.Forms.MouseButtons.Right, "35;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'SQLdmDesktopClient.DeleteDemo' at 67;9.", repo.SQLdmDesktopClient.DeleteDemoInfo, new RecordItemIndex(8));
            repo.SQLdmDesktopClient.DeleteDemo.Click(System.Windows.Forms.MouseButtons.Right, "67;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'ExceptionMessageBoxForm.Button1' at 25;10.", repo.ExceptionMessageBoxForm.Button1Info, new RecordItemIndex(9));
            repo.ExceptionMessageBoxForm.Button1.Click(System.Windows.Forms.MouseButtons.Right, "25;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'ExceptionMessageBoxForm.Button1' at 25;10.", repo.ExceptionMessageBoxForm.Button1Info, new RecordItemIndex(10));
            repo.ExceptionMessageBoxForm.Button1.Click(System.Windows.Forms.MouseButtons.Right, "25;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ExceptionMessageBoxForm.Button1' at 42;9.", repo.ExceptionMessageBoxForm.Button1Info, new RecordItemIndex(11));
            repo.ExceptionMessageBoxForm.Button1.Click("42;9");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
