///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace NewDM2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ToolTip1 recording.
    /// </summary>
    [TestModule("bfed3c54-6d50-4f21-82c2-b864014c2c74", ModuleType.Recording, 1)]
    public partial class ToolTip1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the NewDM2Repository repository.
        /// </summary>
        public static NewDM2Repository repo = NewDM2Repository.Instance;

        static ToolTip1 instance = new ToolTip1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ToolTip1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ToolTip1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ExceptionMessageBoxForm.ShowDetails' at 11;3.", repo.ExceptionMessageBoxForm.ShowDetailsInfo, new RecordItemIndex(0));
            repo.ExceptionMessageBoxForm.ShowDetails.Click("11;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ExceptionMessageBoxForm.ShowDetails' at 9;8.", repo.ExceptionMessageBoxForm.ShowDetailsInfo, new RecordItemIndex(1));
            repo.ExceptionMessageBoxForm.ShowDetails.Click("9;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ExceptionMessageBoxForm.ShowDetails' at 9;8.", repo.ExceptionMessageBoxForm.ShowDetailsInfo, new RecordItemIndex(2));
            repo.ExceptionMessageBoxForm.ShowDetails.Click("9;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ExceptionMessageBoxForm.CellColumnHeaderTotalActiveAlertCoun' at 0;13.", repo.ExceptionMessageBoxForm.CellColumnHeaderTotalActiveAlertCounInfo, new RecordItemIndex(3));
            repo.ExceptionMessageBoxForm.CellColumnHeaderTotalActiveAlertCoun.MoveTo("0;13");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ExceptionMessageBoxForm.CellColumnHeaderTotalActiveAlertCoun' at 0;13.", repo.ExceptionMessageBoxForm.CellColumnHeaderTotalActiveAlertCounInfo, new RecordItemIndex(4));
            repo.ExceptionMessageBoxForm.CellColumnHeaderTotalActiveAlertCoun.MoveTo("0;13");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ExceptionMessageBoxForm.CellColumnHeaderTotalActiveAlertCoun' at 189;14.", repo.ExceptionMessageBoxForm.CellColumnHeaderTotalActiveAlertCounInfo, new RecordItemIndex(5));
            repo.ExceptionMessageBoxForm.CellColumnHeaderTotalActiveAlertCoun.MoveTo("189;14");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ExceptionMessageBoxForm.CellColumnHeaderTotalActiveAlertCoun' at 25;36.", repo.ExceptionMessageBoxForm.CellColumnHeaderTotalActiveAlertCounInfo, new RecordItemIndex(6));
            repo.ExceptionMessageBoxForm.CellColumnHeaderTotalActiveAlertCoun.MoveTo("25;36");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ExceptionMessageBoxForm.CellColumnHeaderTotalActiveAlertCoun' at 472;178.", repo.ExceptionMessageBoxForm.CellColumnHeaderTotalActiveAlertCounInfo, new RecordItemIndex(7));
            repo.ExceptionMessageBoxForm.CellColumnHeaderTotalActiveAlertCoun.MoveTo("472;178");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ExceptionMessageBoxForm.TextEditorEditArea' at 28;9.", repo.ExceptionMessageBoxForm.TextEditorEditAreaInfo, new RecordItemIndex(8));
            repo.ExceptionMessageBoxForm.TextEditorEditArea.Click("28;9");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
